### ISSUE TITLE
master branch is incompatible with scarthgap

### ISSUE THREAD

**Issue by shahimvedaei** [akuster/meta-odroid#112]
Scarthgap is a LTS version; however, I did not find a dedicated Tag for this version. Hence, I used the master branch in which looks like it should be compatible with scarthgap.

conf/layer.conf
`LAYERSERIES_COMPAT_odroid-layer = "nanbield scarthgap styhead"`

But It get the folllowing error.
```
Sstate summary: Wanted 1125 Local 0 Mirrors 0 Missed 1125 Current 624 (0% match, 35% complete)####################################################################################                  | ETA:  0:00:00
Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:02
NOTE: Executing Tasks
ERROR: u-boot-1_2024.01-r0 do_compile: UNPACKDIR not defined, unable to package
ERROR: u-boot-1_2024.01-r0 do_compile: Unable to open ${UNPACKDIR}/boot.cmd
ERROR: Logfile of failure stored in: /home/user/poky/build/tmp/work/odroid_xu4-poky-linux-gnueabi/u-boot/2024.01/temp/log.do_compile.3013
ERROR: Task (/home/user/poky/meta/recipes-bsp/u-boot/u-boot_2024.01.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2083 tasks of which 1868 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
```

As of new requirement for Styhead, the WORKDIR is replaced with UNPACKDIR. However, this change leads to an error for Scarthgap.

Kindly, create a new Tag/Branch for Scarthgap as it is a LTS version, and use the old WORKDIR method.

**Comment by zultron** [comment]
I ran into the same problem.  You can directly check out the `3ce0d70` commit, directly before the `UNPACKDIR` changes, and see if that works for you.  It worked for me, building for an HC1.

I created my own `scarthgap` branch, linked below.  The branch starts from that commit, and cherry-picks all commits from `master` branch that aren't `styhead`-specific.
https://github.com/zultron/meta-odroid/tree/scarthgap

**Comment by zultron** [comment]
I believe commit e87ef97 also applies only to `styhead`, and not to `nanbield`.

```
$ bitbake-layers show-recipes
NOTE: Starting bitbake server...
NOTE: Unable to use interactive mode for this terminal, using fallback
Loading cache: 100% |##################################################| Time: 0:00:01
Loaded 4836 entries from dependency cache.
ERROR: No recipes in default available for:
  [...]/meta-odroid/recipes-graphics/mesa/mesa.bbappend

Summary: There was 1 ERROR message, returning a non-zero exit code.
Traceback (most recent call last):
  File "[...]/poky/bitbake/bin/bitbake-layers", line 95, in <module>
    ret = main()
  File "[...]/poky/bitbake/bin/bitbake-layers", line 85, in main
    tinfoil.parse_recipes()
  File "[...]/poky/bitbake/lib/bb/tinfoil.py", line 449, in parse_recipes
    self.run_actions(config_params)
  File "[...]/poky/bitbake/lib/bb/tinfoil.py", line 432, in run_actions
    raise TinfoilUIException(ret)
bb.tinfoil.TinfoilUIException: 1
```

(My first foray into Yocto, took me a while to figure out what's going on there.  xD )
